# CREAR UNA VISTA LLAMADA VENDEDORESA QUE INCLUIRA B TODOS LOS VENDEDORES DEL 
# GRUPO QUE SE LLAME VENDEDORESB
CREATE VIEW VendedoresB AS
SELECT * FROM vendedores WHERE grupo_id IN
(SELECT id FROM grupos WHERE nombre = 'Vendedores B');

