# MOSTRAR TODOS LOS REGISTROS DE UNA TABLA #
SELECT email, nombre, apellidos FROM usuarios;

# MOSTRAR TODOS LOS CAMPOS #
SELECT * FROM usuarios;

# OPERADORES ARITMETICOS #
SELECT email, (7+7) AS 'OPERACION' FROM usuarios;
SELECT email, (7+7) AS 'OPERACION' FROM usuarios ORDER BY id DESC;
SELECT email, (7+7) AS 'OPERACION' FROM usuarios ORDER BY id ASC;



# FUNCIONES MATEMATICAS #
SELECT ABS(7) AS 'OPERACION' FROM usuarios;
SELECT CEIL(7.34) AS 'OPERACION' FROM usuarios; # REDONDEA AL ENTERO MAYOR #
SELECT FLOOR(7.34) AS 'OPERACION' FROM usuarios; # REDONDEA AL ENTERO MENOR #
SELECT PI() AS 'OPERACION' FROM usuarios; # SACA EL NUMERO PI #
SELECT RAND() AS 'OPERACION' FROM usuarios; # GENERA NUMEROS ALEATORIOS #
SELECT RAUND(7.91) AS 'OPERACION' FROM usuarios; # REDONDEO #
SELECT RAUND(7.91, 1) AS 'OPERACION' FROM usuarios; # REDONDEO, EL 2DO PARAMETRO ES LA CANTIDAD DE DECIMALES #
SELECT TRUNCATE(7.91, 2) AS 'OPERACION' FROM usuarios; # TRUNCA EL NUMERO DE DECIMALES QUE DESEO TENER #

# FUNCIONES PARA TEXTO #
SELECT nombre FROM usuarios;
SELECT UPPER(nombre) FROM usuarios; # MAYUSCULA #
SELECT LOWER(nombre) FROM usuarios; # MINUSCULA #
SELECT CONCAT(nombre, ' ', apellidos) FROM usuarios; # CONCATENAR #
SELECT CONCAT(nombre, ' ', apellidos) AS 'CONVERSION' FROM usuarios; # CONCATENACION CON ENCABEZADO DE TABLA #
SELECT UPPER(CONCAT(nombre, ' ', apellidos)) AS 'CONVERSION' FROM usuarios; # MAYUSCULA Y CONTATENA #
SELECT LENGTH(CONCAT(nombre, ' ', apellidos)) AS 'CONVERSION' FROM usuarios; # LARGO DE LA  CADENA #
SELECT email, LENGTH(CONCAT(nombre, ' ', apellidos)) AS 'CONVERSION' FROM usuarios; # LARGO DE LA  CADENA MAS COLUMNA EMAIL #
SELECT CONCAT('    ', nombre, ' ', apellidos, '    ') AS 'CONVERSION' FROM usuarios; # LARGO DE LA  CADENA MAS COLUMNA EMAIL #
SELECT TRIM(CONCAT('    ', nombre, ' ', apellidos, '    ')) AS 'CONVERSION' FROM usuarios; # ELIMINA ESPACIOS ANTES Y DESPUES DE LA CADENA #


# FUNCIONES GENERALES #
SELECT * FROM usuarios;
SELECT email, ISNULL(apellidos) FROM usuarios; # DEBUELVE UN BOOLEANO DE SI HAY NULOS #
SELECT email, STRCMP('HOLA', 'HOLA') FROM usuarios; # DEBUELVE UN BOOLEANO DE SI HAY DATOS IGUALES #
SELECT USER() FROM usuarios; # SACA EL USUARIO Y SERVIDOR EN EL QUE ACTUA EL USUARIO #
SELECT IFNULL(apellidos, 'ESTE CAMPO ESTA VACIO') FROM usuarios; # PONE UN STRING EN EL CAMPO BASIO #