# MODIFICAR FILAS / ACTUALIZAR BASE DE DATOS #
UPDATE usuarios SET fecha = '1996-07-17' WHERE id = 1; # ACTUALIAR FECHAR POR ID #
UPDATE usuarios SET apellidos = 'PEREZ' WHERE id = 4; # ACTUALIAR APELLIDOS POR ID #
