# CONSULTA CON UNA CONDICION #
SELECT * FROM usuarios;
SELECT * FROM usuarios WHERE email = 'joansaro.sant@gmail.com'; # CONSULTA EL REGISTRO O REGISTROS CON EL CONTENIDO QUE SE INDICA #

/*
OPERADORES DE COMPARACION
IGUAL           = 
DISTINTO        !=
MAYOR QUE       >
MENOR QUE       <
MENOR O IGUAL   <=
MAYOR O IGUAL   >=
ENTRE           between A and B
EN              in
ES NULO         is null
NO NULO         is not null
COMO(contenga)  like
NO ES COMO      not like
*/

/*
OPERADORES LOGICOS
O               OR
Y               AND
NO              NOT
*/

/*
COMODINES
CUALQUIER CANTIDAD DE CARACTERES    %
UN CARACTER DESCONOCIDO             _

*/

# EJEMPLOS #
# MOSTRAR NOMBRES Y APELLIDOS DE TODOS LOS USUARIOS REGISTRADOS EN 2020 #
SELECT nombre, apellidos FROM usuarios WHERE YEAR(fecha) = 2020; # MUESTRA LOS REGISTROS HECHOS EN EL AÑO INDICADO #

# MOSTRAR NOMBRES Y APELLIDOS DE TODOS LOS USUARIOS QUE NO SE REGISTRADOS EN 2020 #
SELECT nombre, apellidos FROM usuarios WHERE YEAR(fecha) != 2020; # MUESTRA LOS REGISTROS NO HECHOS EN EL AÑO INDICADO SIN DATOS NULOS#

SELECT nombre, apellidos FROM usuarios WHERE YEAR(fecha) != 2020 OR ISNULL(fecha); # MUESTRA LOS REGISTROS NO HECHOS EN EL AÑO INDICADO CON DATOS NULOS#


# MOSTRAR EL EMAIL DE LOS USUARIOS CUYO APELLIDO CONTENGA LA LETRA A Y ADEMAS SU CONTRASEÑA SEA 1234 #
SELECT email FROM usuarios WHERE apellido LIKE '%a%' AND password = '1234';

# SACAR TODOS LOS REGISTROS DE LA TABLA USUARIOS CUYO AÑO SEA PAR #
SELECT * FROM usuarios WHERE (YEAR(fecha)%2 = 0);

# SACAR TODOS LOS REGISTROS DE LA TABLA USUARIOS CUYO NOMBRE TENGA MAS DE 5 LETRAS Y QUE SE AYA REGISTRADO ANTES DE 2020, Y MOSTRAR EL NOMBRE EN MAYUSCULAS  #
SELECT UPPER(nombre) AS 'NOMBRE', apellidos FROM usuarios WHERE LENGTH(nombre) > 5 AND YEAR(fecha) <= 2020; 



# ORDENAR #
SELECT * FROM usuarios ORDER BY fecha ASC; # ORDENA POR #
 
SELECT * FROM usuarios LIMIT 3; # LIMITA EL NUMERO DE REGISTROS (PRIMEROS 3 REGISTROS)#
SELECT * FROM usuarios LIMIT 2,3; # LIMITA EL NUMERO DE REGISTROS (ENTRE UN INTERVALO)#