# MOSTRAR LOS DATOS DEL VENDEDOR CON MAS ANTIGUEDAD EN EL CONCECIONARIO
SELECT * FROM vendedores ORDER BY fecha ASC LIMIT 1;


# EJERCICIO 30+
# OBTENER LOS COCHES CON MAS UNIDADES VENDIDAS

SELECT * FROM coches WHERE id IN (
SELECT coche_id FROM encargos WHERE cantidad IN
(SELECT MAX(cantidad) FROM encargos));
