# OBTENER LOS NOMBRES Y CIUDADES DE LOS CLIENTES CON ENCARGOS CON ENCARGOS DE 3 
# UNIDADES O MAS#
SELECT nombre, ciudad FROM clientes WHERE id IN
(SELECT cliente_id FROM encargos WHERE cantidad >= 3);