# VISUALIZAR EL APELLIDO DE LOS VENDEDORES, FECHA DE ALTA, NUMERO DE GRUPO, 
# ORNEDADOS POR FECHA DESENDENTE, MOSTRAR LOS 4 ULTIMOS

SELECT apellidos, fecha_alta, grupo_id FROM vendedores ORDER BY fecha_alta DESC LIMIT 4;