# MOSTRAR LOS 2 CLIENTES QUE MAS CARGOS HAN PEDIDOS Y MOSTRAR CUANTOS HICIERON #

SELECT c.nombre, COUNT(e.id) FROM encargos e
INNER JOIN clientes c ON c.id = e.cliente_id
GROUP BY cliente_id ORDER BY 2 DESC LIMIT 2;